@startuml use_case
skinparam actorStyle awesome
left to right direction

actor Student

package "GPA Calculator" {
  Student --> (Sign Up)
  Student --> (Log In)
  Student --> (Log Out)
  Student --> (View Enrollments)
  Student --> (Add Course Enrollment)
  Student --> (Update Course Grade)
  Student --> (Delete Course Enrollment)
  Student --> (View GPA)
}

@enduml